#header()

#set($command = $helper.getByName($command-name, $robot))

\#include "#class($command.name).h"

#class($command.name)::#class($command.name)() {

#@autogenerated_code("requires", "	")
#parse("${exporter-path}Command-requires.cpp")
#end
}

void #class($command.name)::Initialize() {
	
}

void #class($command.name)::Execute() {
#@autogenerated_code("execute", "        ")
#parse("${exporter-path}SetpointCommand-execute.cpp")
#end
}

bool #class($command.name)::IsFinished() {
#@autogenerated_code("isFinished", "        ")
#parse("${exporter-path}SetpointCommand-isFinished.cpp")
#end
}

void #class($command.name)::End() {
	
}

void #class($command.name)::Interrupted() {

}
