#header()
package ${package}.commands;
#set($command = $helper.getByName($command-name, $robot))

import edu.wpi.first.wpilibj.command.Command;
import ${package}.Robot;

public class  #class($command.name) extends Command {

    public #class($command.name)() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
#@autogenerated_code("requires", "        ")
#parse("${exporter-path}Command-requires.java")
#end
    }

    protected void initialize() {
    }

    protected void execute() {
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    }

    protected void interrupted() {
    }
}
