#header()

package ${package}.commands;

import edu.wpi.first.wpilibj.command.PIDCommand;
import ${package}.Robot;
import ${package}.RobotMap;

#set($command = $helper.getByName($command-name, $robot))

public class  #class($command.name) extends PIDCommand {

    public #class($command.name)() {
#@autogenerated_code("pid", "        ")
#parse("${exporter-path}PIDCommand-pid.java")
#end
#@autogenerated_code("requires", "        ")
#parse("${exporter-path}Command-requires.java")
#end
    }

    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;
		
#@autogenerated_code("source", "        ")
#parse("${exporter-path}PIDCommand-source.java")
#end
    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);
		
#@autogenerated_code("output", "        ")
#parse("${exporter-path}PIDCommand-output.java")
#end
    }

    protected void initialize() {
    }

    protected void execute() {
    }

    protected boolean isFinished() {
        return false;
    }

    protected void end() {
    }

    protected void interrupted() {
    }
}
