#header()

package ${package}.commands;
#set($command = $helper.getByName($command-name, $robot))

import edu.wpi.first.wpilibj.command.Command;
import ${package}.Robot;

public class  #class($command.name) extends Command {

    public #class($command.name)() {
#@autogenerated_code("requires", "        ")
#parse("${exporter-path}Command-requires.java")
#end
    }

    protected void initialize() {
    }

    protected void execute() {
#@autogenerated_code("execute", "        ")
#parse("${exporter-path}SetpointCommand-execute.java")
#end
    }

    protected boolean isFinished() {
#@autogenerated_code("isFinished", "        ")
#parse("${exporter-path}SetpointCommand-isFinished.java")
#end
    }

    protected void end() {
    }

    protected void interrupted() {
    }
}
