#header()
package ${package}.subsystems;
#set($subsystem = $helper.getByName($subsystem-name, $robot))

import ${package}.RobotMap;
import ${package}.commands.*;
${helper.getImports($subsystem, "RobotMap")}
import edu.wpi.first.wpilibj.command.Subsystem;

public class #class($subsystem.name) extends Subsystem {
#@autogenerated_code("declarations", "    ")
#parse("${exporter-path}Subsystem-declarations.java")
#end

  
public void initDefaultCommand() {
#@autogenerated_code("default_command", "        ")
#parse("${exporter-path}Subsystem-default_command.java")
#end
	
    }
}

